<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<%@ taglib prefix="fmt" uri="jakarta.tags.fmt" %>
<!DOCTYPE html><html lang="vi"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Quản lý khách hàng</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" rel="stylesheet"><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/style.css">
<style>.avatar{width:40px;height:40px;border-radius:50%;display:grid;place-items:center;background:#dbeafe;color:#2563eb;font-weight:700}.stat-card{border:0;box-shadow:0 1px 4px rgba(15,23,42,.06)}</style></head><body>
<div class="container-fluid p-0 d-flex"><div id="sidebar-placeholder"></div><main class="main-content">
<div class="topbar d-flex justify-content-between align-items-center"><div><h1 class="h4 m-0 fw-bold">👥 Quản Lý Khách Hàng</h1><small class="text-muted">Dữ liệu trực tiếp từ PostgreSQL</small></div><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#customerModal"><i class="fa-solid fa-user-plus me-2"></i>Thêm khách hàng</button></div>
<div class="content">
<c:if test="${not empty flashSuccess}"><div class="alert alert-success"><c:out value="${flashSuccess}"/></div></c:if><c:if test="${not empty flashError}"><div class="alert alert-danger"><c:out value="${flashError}"/></div></c:if>
<div class="row g-3 mb-4"><div class="col-sm-6"><div class="card stat-card"><div class="card-body"><small class="text-muted">Khách hàng hiển thị</small><div class="fs-3 fw-bold">${customers.size()}</div></div></div></div><div class="col-sm-6"><div class="card stat-card"><div class="card-body"><small class="text-muted">Khách thân thiết</small><div class="fs-3 fw-bold text-success"><c:set var="loyalCount" value="0"/><c:forEach items="${customers}" var="customer"><c:if test="${customer.customerType == 'LOYAL'}"><c:set var="loyalCount" value="${loyalCount + 1}"/></c:if></c:forEach>${loyalCount}</div></div></div></div></div>
<div class="card border-0 shadow-sm"><div class="card-body border-bottom"><form method="get" class="row g-2"><div class="col-lg-7"><input class="form-control" name="q" value="<c:out value='${keyword}'/>" placeholder="Tìm theo mã, tên hoặc số điện thoại..."></div><div class="col-sm-6 col-lg-3"><select class="form-select" name="customerType"><option value="">Tất cả nhóm</option><option value="LOYAL" ${selectedCustomerType == 'LOYAL' ? 'selected' : ''}>Thân thiết</option><option value="REGULAR" ${selectedCustomerType == 'REGULAR' ? 'selected' : ''}>Khách thường</option></select></div><div class="col-sm-6 col-lg-2 d-flex gap-2"><button class="btn btn-outline-primary flex-fill">Lọc</button><a class="btn btn-light border" href="${pageContext.request.contextPath}/customers"><i class="fa-solid fa-rotate-left"></i></a></div></form></div>
<div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead class="table-light"><tr><th class="ps-4">Khách hàng</th><th>Mã KH</th><th>Liên hệ</th><th>Nhóm</th><th class="text-center">Lượt mua</th><th>Tổng chi tiêu</th><th>Mua gần nhất</th><th class="text-end pe-4">Thao tác</th></tr></thead><tbody>
<c:forEach items="${customers}" var="customer"><tr><td class="ps-4"><div class="d-flex align-items-center gap-2"><div class="avatar"><i class="fa-solid fa-user"></i></div><div><div class="fw-semibold"><c:out value="${customer.fullName}"/></div><small class="text-muted"><c:out value="${customer.email}" default="Chưa có email"/></small></div></div></td><td><span class="badge bg-light text-dark border">${customer.code}</span></td><td>${customer.phone}</td><td><span class="badge ${customer.customerType == 'LOYAL' ? 'bg-success-subtle text-success' : 'bg-secondary-subtle text-secondary'}">${customer.customerType == 'LOYAL' ? 'Thân thiết' : 'Thường'}</span></td><td class="text-center">${customer.purchaseCount}</td><td class="fw-semibold"><fmt:formatNumber value="${customer.totalSpent}" pattern="#,#00"/> đ</td><td><c:choose><c:when test="${not empty customer.lastPurchaseAt}">${customer.lastPurchaseAt.toLocalDate()}</c:when><c:otherwise><span class="text-muted">Chưa mua</span></c:otherwise></c:choose></td><td class="text-end pe-4"><a class="btn btn-sm btn-outline-primary" href="${pageContext.request.contextPath}/customers?editId=${customer.id}"><i class="fa-solid fa-pen"></i></a></td></tr></c:forEach>
<c:if test="${empty customers}"><tr><td colspan="8" class="text-center text-muted py-5">Không tìm thấy khách hàng.</td></tr></c:if>
</tbody></table></div><div class="card-footer bg-white border-0 small text-muted">Hiển thị ${customers.size()} khách hàng</div></div>
</div></main></div>

<div class="modal fade" id="customerModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><form method="post" action="${pageContext.request.contextPath}/customers"><input type="hidden" name="csrfToken" value="${sessionScope.csrfToken}"><div class="modal-header"><h5 class="modal-title fw-bold">${empty editingCustomer ? 'Thêm khách hàng' : 'Sửa khách hàng'}</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="id" value="${editingCustomer.id}">
<div class="mb-3"><label class="form-label fw-semibold">Họ và tên</label><input class="form-control" name="fullName" required value="<c:out value='${editingCustomer.fullName}'/>"></div>
<div class="row g-3"><div class="col-6"><label class="form-label fw-semibold">Số điện thoại</label><input class="form-control" name="phone" required value="<c:out value='${editingCustomer.phone}'/>"></div><div class="col-6"><label class="form-label fw-semibold">Giới tính</label><select class="form-select" name="gender"><option value="">Chưa chọn</option><option value="MALE" ${editingCustomer.gender == 'MALE' ? 'selected' : ''}>Nam</option><option value="FEMALE" ${editingCustomer.gender == 'FEMALE' ? 'selected' : ''}>Nữ</option><option value="OTHER" ${editingCustomer.gender == 'OTHER' ? 'selected' : ''}>Khác</option></select></div></div>
<div class="mt-3"><label class="form-label fw-semibold">Email</label><input type="email" class="form-control" name="email" value="<c:out value='${editingCustomer.email}'/>"></div><div class="mt-3"><label class="form-label fw-semibold">Địa chỉ</label><textarea class="form-control" name="address" rows="2"><c:out value="${editingCustomer.address}"/></textarea></div><div class="mt-3"><label class="form-label fw-semibold">Nhóm khách</label><select class="form-select" name="customerType"><option value="REGULAR" ${editingCustomer.customerType == 'REGULAR' ? 'selected' : ''}>Khách thường</option><option value="LOYAL" ${editingCustomer.customerType == 'LOYAL' ? 'selected' : ''}>Thân thiết</option></select></div>
</div><div class="modal-footer"><a class="btn btn-light" href="${pageContext.request.contextPath}/customers">Hủy</a><button class="btn btn-primary">Lưu khách hàng</button></div></form></div></div></div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script><script>fetch('${pageContext.request.contextPath}/common/sidebar').then(r=>r.text()).then(html=>{document.getElementById('sidebar-placeholder').outerHTML=html;document.querySelector('.sidebar-nav a[href$="/customers"]')?.classList.add('active');});<c:if test="${not empty editingCustomer}">bootstrap.Modal.getOrCreateInstance(document.getElementById('customerModal')).show();</c:if></script></body></html>
