<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %><%@ taglib prefix="fmt" uri="jakarta.tags.fmt" %>
<!DOCTYPE html><html lang="vi"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Quản lý kho</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" rel="stylesheet"><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/style.css"><style>.metric{border:0;box-shadow:0 1px 4px rgba(15,23,42,.06)}.change-positive{color:#16a34a}.change-negative{color:#dc2626}</style></head><body>
<div class="container-fluid p-0 d-flex"><div id="sidebar-placeholder"></div><main class="main-content"><div class="topbar d-flex justify-content-between align-items-center"><div><h1 class="h4 m-0 fw-bold">🏬 Quản Lý Kho</h1><small class="text-muted">Mọi thay đổi đều được ghi lịch sử</small></div><div class="d-flex gap-2"><button class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#adjustModal">Điều chỉnh tồn</button><a class="btn btn-primary" href="${pageContext.request.contextPath}/purchase-orders"><i class="fa-solid fa-truck-ramp-box me-2"></i>Tạo phiếu nhập</a></div></div>
<div class="content"><c:if test="${not empty flashSuccess}"><div class="alert alert-success"><c:out value="${flashSuccess}"/></div></c:if><c:if test="${not empty flashError}"><div class="alert alert-danger"><c:out value="${flashError}"/></div></c:if>
<div class="row g-3 mb-4"><div class="col-sm-4"><div class="card metric"><div class="card-body"><small class="text-muted">Tổng tồn kho</small><div class="fs-3 fw-bold">${totalStock}</div></div></div></div><div class="col-sm-4"><div class="card metric"><div class="card-body"><small class="text-muted">Cần nhập thêm</small><div class="fs-3 fw-bold text-warning">${lowStock}</div></div></div></div><div class="col-sm-4"><div class="card metric"><div class="card-body"><small class="text-muted">Hết hàng</small><div class="fs-3 fw-bold text-danger">${outOfStock}</div></div></div></div></div>
<ul class="nav nav-pills mb-3"><li class="nav-item"><button class="nav-link active" data-bs-toggle="pill" data-bs-target="#stockTab">Tồn kho hiện tại</button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="pill" data-bs-target="#historyTab">Lịch sử kho</button></li></ul>
<div class="tab-content"><div class="tab-pane fade show active" id="stockTab"><div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead class="table-light"><tr><th class="ps-4">Sản phẩm</th><th>Danh mục</th><th>Tồn hiện tại</th><th>Tồn tối thiểu</th><th>Trạng thái</th><th>Cập nhật cuối</th></tr></thead><tbody><c:forEach items="${products}" var="product"><tr><td class="ps-4"><div class="fw-semibold"><c:out value="${product.name}"/></div><small class="text-muted">${product.code}</small></td><td><c:out value="${product.categoryName}"/></td><td class="fw-bold">${product.stockQuantity} ${product.unit}</td><td>${product.minimumStock}</td><td><c:choose><c:when test="${product.outOfStock}"><span class="badge bg-danger">Hết hàng</span></c:when><c:when test="${product.lowStock}"><span class="badge bg-warning text-dark">Cần nhập</span></c:when><c:otherwise><span class="badge bg-success">Đủ hàng</span></c:otherwise></c:choose></td><td class="small text-muted">${product.updatedAt.toLocalDateTime()}</td></tr></c:forEach></tbody></table></div></div></div>
<div class="tab-pane fade" id="historyTab"><div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table align-middle mb-0"><thead class="table-light"><tr><th class="ps-4">Thời gian</th><th>Sản phẩm</th><th>Loại</th><th>Thay đổi</th><th>Tồn trước → sau</th><th>Lý do/Tham chiếu</th></tr></thead><tbody><c:forEach items="${transactions}" var="transaction"><tr><td class="ps-4 small text-muted">${transaction.createdAt.toLocalDateTime()}</td><td><div class="fw-semibold"><c:out value="${transaction.productName}"/></div><small>${transaction.productCode}</small></td><td>${transaction.transactionType}</td><td class="fw-bold ${transaction.quantityChange > 0 ? 'change-positive' : 'change-negative'}">${transaction.quantityChange > 0 ? '+' : ''}${transaction.quantityChange}</td><td>${transaction.stockBefore} → ${transaction.stockAfter}</td><td><c:out value="${transaction.reason}"/><c:if test="${not empty transaction.referenceType}"><small class="d-block text-muted">${transaction.referenceType} #${transaction.referenceId}</small></c:if></td></tr></c:forEach><c:if test="${empty transactions}"><tr><td colspan="6" class="text-center text-muted py-5">Chưa có biến động kho.</td></tr></c:if></tbody></table></div></div></div></div>
</div></main></div>

<div class="modal fade" id="adjustModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><form method="post" action="${pageContext.request.contextPath}/inventory"><input type="hidden" name="csrfToken" value="${sessionScope.csrfToken}"><div class="modal-header"><h5 class="modal-title fw-bold">Điều chỉnh tồn kho</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="action" value="adjust"><div class="mb-3"><label class="form-label fw-semibold">Sản phẩm</label><select class="form-select" name="productId" required><option value="">Chọn sản phẩm</option><c:forEach items="${products}" var="product"><option value="${product.id}">${product.code} — <c:out value="${product.name}"/> (hiện có ${product.stockQuantity})</option></c:forEach></select></div><div class="mb-3"><label class="form-label fw-semibold">Tồn sau kiểm kê</label><input type="number" min="0" class="form-control" name="newStock" required></div><div><label class="form-label fw-semibold">Lý do</label><textarea class="form-control" name="reason" rows="2" required></textarea></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Hủy</button><button class="btn btn-primary">Lưu điều chỉnh</button></div></form></div></div></div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script><script>fetch('${pageContext.request.contextPath}/common/sidebar').then(r=>r.text()).then(html=>{document.getElementById('sidebar-placeholder').outerHTML=html;document.querySelector('.sidebar-nav a[href$="/inventory"]')?.classList.add('active');});</script></body></html>
