<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %><%@ taglib prefix="fmt" uri="jakarta.tags.fmt" %>
<!doctype html><html lang="vi"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Hóa đơn</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" rel="stylesheet"><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/style.css"></head><body>
<div class="container-fluid p-0 d-flex"><div id="sidebar-placeholder"></div><main class="main-content"><div class="topbar"><h1 class="h4 m-0 fw-bold">🧾 Quản lý hóa đơn</h1></div><div class="content">
<c:if test="${not empty flashSuccess}"><div class="alert alert-success"><c:out value="${flashSuccess}"/></div></c:if><c:if test="${not empty flashError}"><div class="alert alert-danger"><c:out value="${flashError}"/></div></c:if>
<div class="card border-0 shadow-sm"><div class="card-body border-bottom"><form class="row g-2"><div class="col-md-7"><input class="form-control" name="q" value="<c:out value='${keyword}'/>" placeholder="Tìm mã hóa đơn hoặc tên khách..."></div><div class="col-md-3"><select class="form-select" name="status"><option value="">Tất cả trạng thái</option><option value="PAID" ${selectedStatus=='PAID'?'selected':''}>Đã thanh toán</option><option value="CANCELLED" ${selectedStatus=='CANCELLED'?'selected':''}>Đã hủy</option></select></div><div class="col-md-2"><button class="btn btn-primary w-100">Lọc</button></div></form></div>
<div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead class="table-light"><tr><th class="ps-4">Mã HĐ</th><th>Thời gian</th><th>Khách hàng</th><th>Thu ngân</th><th>Thanh toán</th><th>Tổng tiền</th><th>Trạng thái</th><th></th></tr></thead><tbody><c:forEach items="${invoices}" var="i"><tr><td class="ps-4 fw-semibold">${i.code}</td><td>${i.createdAt.toLocalDateTime()}</td><td><c:out value="${i.customerName}" default="Khách lẻ"/></td><td><c:out value="${i.cashierName}" default="—"/></td><td>${i.paymentMethod}</td><td class="fw-bold"><fmt:formatNumber value="${i.totalAmount}" pattern="#,#00"/> đ</td><td><span class="badge ${i.status=='PAID'?'bg-success-subtle text-success':'bg-danger-subtle text-danger'}">${i.status=='PAID'?'Đã thanh toán':'Đã hủy'}</span></td><td><a class="btn btn-sm btn-outline-primary" href="?id=${i.id}">Chi tiết</a></td></tr></c:forEach><c:if test="${empty invoices}"><tr><td colspan="8" class="text-center text-muted py-5">Chưa có hóa đơn.</td></tr></c:if></tbody></table></div></div>
</div></main></div>
<c:if test="${not empty selectedInvoice}"><div class="modal fade" id="detailModal"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><div class="modal-header"><div><h5 class="modal-title">Hóa đơn ${selectedInvoice.code}</h5><small class="text-muted">${selectedInvoice.createdAt.toLocalDateTime()}</small></div><a class="btn-close" href="${pageContext.request.contextPath}/invoices"></a></div><div class="modal-body"><div class="row mb-3"><div class="col">Khách: <strong><c:out value="${selectedInvoice.customerName}" default="Khách lẻ"/></strong></div><div class="col text-end">Thanh toán: <strong>${selectedInvoice.paymentMethod}</strong></div></div><div class="table-responsive"><table class="table"><thead><tr><th>Sản phẩm</th><th class="text-center">SL</th><th class="text-end">Đơn giá</th><th class="text-end">Thành tiền</th></tr></thead><tbody><c:forEach items="${selectedInvoice.details}" var="d"><tr><td>${d.productCode} — <c:out value="${d.productName}"/></td><td class="text-center">${d.quantity}</td><td class="text-end"><fmt:formatNumber value="${d.unitPrice}" pattern="#,#00"/> đ</td><td class="text-end"><fmt:formatNumber value="${d.lineTotal}" pattern="#,#00"/> đ</td></tr></c:forEach></tbody><tfoot><tr><th colspan="3" class="text-end">Tổng cộng</th><th class="text-end text-danger"><fmt:formatNumber value="${selectedInvoice.totalAmount}" pattern="#,#00"/> đ</th></tr></tfoot></table></div></div><div class="modal-footer"><a class="btn btn-light" href="${pageContext.request.contextPath}/invoices">Đóng</a><c:if test="${selectedInvoice.status=='PAID' && sessionScope.currentUser.role=='ADMIN'}"><form method="post" onsubmit="return confirm('Hủy hóa đơn và hoàn toàn bộ hàng về kho?')"><input type="hidden" name="csrfToken" value="${sessionScope.csrfToken}"><input type="hidden" name="id" value="${selectedInvoice.id}"><button class="btn btn-danger">Hủy hóa đơn & hoàn kho</button></form></c:if></div></div></div></div></c:if>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script><script>fetch('${pageContext.request.contextPath}/common/sidebar').then(r=>r.text()).then(h=>{document.getElementById('sidebar-placeholder').outerHTML=h;document.querySelector('.sidebar-nav a[href$="/invoices"]')?.classList.add('active')});<c:if test="${not empty selectedInvoice}">bootstrap.Modal.getOrCreateInstance(document.getElementById('detailModal')).show();</c:if></script></body></html>
